### ISSUE TITLE
It does not start in dev mode and does not build

### ISSUE THREAD

**Issue by dunnock** [grommet/grommet-cms-boilerplate#68]
```MBP-Maksym:grommet-cms-boilerplate max$ npm run dev

> grommet-cms@0.0.1 dev /Users/max/src/logncode/grommet-cms-boilerplate
> gulp dev

[12:18:31] Requiring external module babel-register
[grommet-toolbox] scsslint option has been deprecated and will be removed in the next major release. SCSS linting is always enabled now.
[12:18:33] Using gulpfile ~/src/logncode/grommet-cms-boilerplate/gulpfile.babel.js
(node:21060) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[12:18:33] Starting 'dev-preprocess'...
[12:18:33] Starting 'preprocess'...
[12:18:33] Starting 'clean'...
[12:18:33] Finished 'clean' after 3.16 ms
[12:18:33] Starting 'generate-icons'...
[12:18:33] Finished 'generate-icons' after 331 μs
[12:18:33] Starting 'jslint'...
Unhandled rejection Error: Failed to load plugin babel: Cannot find module 'eslint-plugin-babel'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.load (/Users/max/src/logncode/grommet-cms-boilerplate/node_modules/eslint/lib/config/plugins.js:114:26)
    at Array.forEach (native)
    at Object.loadAll (/Users/max/src/logncode/grommet-cms-boilerplate/node_modules/eslint/lib/config/plugins.js:136:21)
    at Object.load (/Users/max/src/logncode/grommet-cms-boilerplate/node_modules/eslint/lib/config/config-file.js:505:21)
    at loadConfig (/Users/max/src/logncode/grommet-cms-boilerplate/node_modules/eslint/lib/config.js:64:33)
    at getLocalConfig (/Users/max/src/logncode/grommet-cms-boilerplate/node_modules/eslint/lib/config.js:126:23)
    at Config.getConfig (/Users/max/src/logncode/grommet-cms-boilerplate/node_modules/eslint/lib/config.js:227:22)
    at processText (/Users/max/src/logncode/grommet-cms-boilerplate/node_modules/eslint/lib/cli-engine.js:223:27)
    at CLIEngine.executeOnText (/Users/max/src/logncode/grommet-cms-boilerplate/node_modules/eslint/lib/cli-engine.js:761:26)
    at verify (/Users/max/src/logncode/grommet-cms-boilerplate/node_modules/gulp-eslint/index.js:20:23)
    at Transform._transform (/Users/max/src/logncode/grommet-cms-boilerplate/node_modules/gulp-eslint/index.js:68:18)
    at Transform._read (_stream_transform.js:167:10)```

**Comment by dunnock** [comment]
The issue was my .eslintrc in top folder

**Comment by RyanCCollins** [comment]
Hey @dunnock thanks for letting us know.  Was there something that we should fix?
